name: Sign Artifact with COSE

on:
  workflow_dispatch:
    inputs:
      file_to_sign:
        description: 'Relative path to file to sign'
        required: true
      private_key:
        description: 'Base64-encoded private key (PKCS8 format)'
        required: true

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore and build signer
        run: |
          dotnet build CoseSigner/CoseSigner.csproj --configuration Release

      - name: Decode private key
        run: |
          echo "${{ github.event.inputs.private_key }}" | base64 -d > private_key.pk8

      - name: Sign file with COSE
        run: |
          FILE_TO_SIGN="${{ github.event.inputs.file_to_sign }}"
          OUTPUT_FILE="${FILE_TO_SIGN}}.cose"
          dotnet ./CoseSigner/bin/Release/net8.0/CoseSigner.dll "$FILE_TO_SIGN" "$OUTPUT_FILE" private_key.pk8
          echo "Signed file created: $OUTPUT_FILE"

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-file
          path: ${{ github.event.inputs.file_to_sign }}.cose
