name: Sign Artifact with COSE (Docker)

on:
  workflow_dispatch:
    inputs:
      file_to_sign:
        description: 'Relative path to the file to sign'
        required: true
        type: string

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write private key from secret
        run: |
          echo "${{ secrets.COSE_SIGN_KEY }}" | base64 -d > private_key.pk8

      - name: Build Docker image
        run: |
          docker build -t cose-signer .

      - name: Run COSE signer in Docker
        run: |
          docker run --rm \
            -v "$PWD:/app" \
            cose-signer \
            "${{ github.event.inputs.file_to_sign }}" \
            "${{ github.event.inputs.file_to_sign }}.cose" \
            /app/private_key.pk8

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-file
          path: ${{ github.event.inputs.file_to_sign }}.cose
