name: Sign Artifact with COSE (Python)

on:
  workflow_dispatch:
    inputs:
      file_to_sign:
        description: 'Relative path to the file to sign'
        required: true
        type: string

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up isolated Python environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install pycose cryptography
          pip list | grep -i cose || true
          echo "from pycose.keys.ec2 import EC2Key" > sanity_check.py && python sanity_check.py

      - name: Write private key from secret
        run: |
          echo "${{ secrets.COSE_SIGN_KEY }}" | base64 -d > private_key.pk8

      - name: Sign file using cose_signer.py
        run: |
          source .venv/bin/activate
          python cose_signer.py "${{ github.event.inputs.file_to_sign }}" \
                 "${{ github.event.inputs.file_to_sign }}.cose" \
                 private_key.pk8

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-file
          path: ${{ github.event.inputs.file_to_sign }}.cose
